apiVersion: v1
kind: Secret
metadata:
  name: portfolio-secret
  namespace: portfolio-devops
type: Opaque
data:
<<<<<<< HEAD
  mysql-user: cm9vdA==  
  mysql-password: c2FydGhha0AxMjM=
  mysql-root-password: c2FydGhha0AxMjM=
=======
  # Base64 encoded 'root'
  mysql-user: cm9vdA== 
  
  # Base64 encoded 'sarthak@123' 
  mysql-password: c2FydGhha0AxMjM=
  
  # Base64 encoded 'sarthak@123' (same as mysql-password for root)
  mysql-root-password: c2FydGhha0AxMjM=
  
  # Base64 encoded 'super-secret-key-for-jwt'
>>>>>>> 74d6f8c (Updated project files make Dynamic)
  jwt-secret: c3VwZXItc2VjcmV0LWtleS1mb3Itand0